# Generated by Django 5.1.1 on 2024-10-17 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='published',
        ),
    ]
